[Features]
Teleport=1
Movement=1
AutoClick=1
Timer=1

[Hotkeys]
TeleportMoca1=F1
TeleportMoca2=F2
TeleportAltF4=F4
AutoClick=F7
Walk=>^w
; Run=>^+w
Run=F6
WalkNumpad=F8
Timer48=F3
Exit=>^Esc

[Settings]
ClickDelay=1
Timer48Minutes=48
NumpadInterval=4000